# Generated by Django 6.0.1 on 2026-01-19 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General Election', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_party_nomination', models.BooleanField(default=False)),
                ('party_name', models.CharField(blank=True, max_length=150)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('yearly_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_properties', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('any_police_case', models.BooleanField(default=False)),
                ('dual_citizen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('preferred_symbol_name', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.district')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.voter')),
                ('assigned_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.voter')),
            ],
            options={
                'unique_together': {('election', 'voter')},
            },
        ),
    ]
